# General training loop config
run_name: &run_name 'petting-zoo-rainbow'
train_steps: 3000000
test_frequency: 50000
test_num_episodes: 1
self_play: True
num_agents: 8
stack_size: &stack_size 1
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'PettingZooEnv'
  kwargs:
    env_name: 'pursuit_v3'
    env_family: 'sisl'
    num_players: 8

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agents:
  -
    name: 'RainbowDQNAgent'
    kwargs:
      qnet:
        name: 'ConvNetwork'
        kwargs:
          channels: [ 16 ]
          mlp_layers: [ 128 ]
          kernel_sizes: [ 3 ]
          strides: [ 1 ]
          paddings: [ 0 ]
          normalization_factor: 1
          noisy: True
          std_init: 0.5
      optimizer_fn:
        name: 'Adam'
        kwargs:
          lr: 0.000025
          eps: 0.00003125
      id: 0
      replay_buffer:
        name: 'EfficientCircularBuffer'
        kwargs:
          seed: 43
          capacity: 100000
          stack_size: 1
      discount_rate: .99
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 500
      epsilon_schedule:
        name: 'ConstantSchedule'
        kwargs:
          value: .0
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 100
      seed: 42
      batch_size: 128
      device: 'cpu'
      log_frequency: 100
      double: True
      distributional: False
      dueling: False
      noisy: False
      std_init: .5
      use_eps_greedy: False
      v_min: -25.0
      v_max: 25.0
      atoms: 51

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "online"
