# General training loop config
run_name: &run_name 'probe5-mlp'
train_steps: 300
test_frequency: 10
test_num_episodes: 1
saving_schedule:
  name: 'ConstantSchedule'
  kwargs:
    value: False
save_dir: 'experiment'


# Environment config
environment:
  name: 'Probe5'
  kwargs:
    img: True

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'DQNAgent'
  kwargs:
    qnet:
      name: 'SimpleMLP'
      kwargs:
        hidden_units: 10
        num_hidden_layers: 2
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: 0.1
    id: 0
    replay_buffer:
      name: 'EfficientCircularBuffer'
      kwargs:
        seed: 42
        capacity: 100
        stack_size: 1
    discount_rate: .9
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 5
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.05
        steps: 50
    learn_schedule:
      name: 'ConstantSchedule'
      kwargs:
        value: True
    seed: 42
    batch_size: 16
    device: 'cuda'
    log_frequency: 1

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      offline: False

